general {
    # Command to run to lock the screen
    lock_cmd = pidof hyprlock || hyprlock
    # Command ran before sleep
    before_sleep_cmd = loginctl lock-session
    # Command ran after sleep
    after_sleep_cmd = hyprctl dispatch dpms on
    # Whether to ignore dbus-sent idle-inhibit requests (e.g., from Firefox, Steam)
    ignore_dbus_inhibit = false
    # Whether to ignore systemd-inhibit --what=idle inhibitors
    ignore_systemd_inhibit = false
}

listener {
    # Timeout in seconds (5 minutes)
    timeout = 600
    # Command to run when timeout has passed (e.g., lock screen)
    on-timeout = loginctl lock-session
    # Command to run when activity is detected after timeout has fired
    on-resume = # optional command
}

listener {
    # Timeout in seconds (10 minutes)
    timeout = 600
    # Turn off the screen using DPMS
    on-timeout = hyprctl dispatch dpms off
    # Turn screen back on on resume
    on-resume = hyprctl dispatch dpms on
}

listener {
    # Timeout in seconds (15 minutes)
    timeout = 900
    # Suspend the system
    on-timeout = systemctl suspend
}
